-- phpMyAdmin SQL Dump
-- version 4.4.15.7
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 06, 2018 at 05:01 PM
-- Server version: 5.6.36
-- PHP Version: 7.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blogging`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogs`
--

CREATE TABLE IF NOT EXISTS `blogs` (
  `IDblog` int(11) NOT NULL,
  `blogTitle` text COLLATE utf16_bin NOT NULL,
  `blogBlurb` text COLLATE utf16_bin NOT NULL,
  `blogEntry` text COLLATE utf16_bin NOT NULL,
  `mbrID` int(11) NOT NULL,
  `blogTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf16 COLLATE=utf16_bin;

--
-- Dumping data for table `blogs`
--

INSERT INTO `blogs` (`IDblog`, `blogTitle`, `blogBlurb`, `blogEntry`, `mbrID`, `blogTime`) VALUES
(1, 'Lady Picture Show', 'Heirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute.', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 2, '2018-11-28 19:52:50'),
(2, 'Vasoline', 'Heirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute.', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 3, '2018-11-28 20:35:00'),
(3, 'Creep', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 3, '2018-11-29 20:35:54'),
(4, 'Trippin On a Hole In a Paper Heart', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 4, '2018-11-27 20:35:54'),
(5, 'Dead & Bloated', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 2, '2018-11-26 20:35:54'),
(6, 'Sex Type Thing', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 4, '2018-11-19 20:35:54'),
(7, 'Down', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 3, '2018-11-13 20:35:54'),
(8, 'Big Empty', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 4, '2018-11-13 20:35:54'),
(9, 'Plush', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 3, '2018-11-13 20:35:54'),
(10, 'Interstate Love Song', 'Squid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo', 'Lorem ipsum dolor amet migas marfa eu meggings. Vegan aute pickled cillum laborum roof party, health goth officia yr keffiyeh try-hard. Asymmetrical selvage duis taiyaki craft beer DIY, coloring book eiusmod literally meh fam. Dreamcatcher pour-over adipisicing small batch franzen cliche enamel pin live-edge kinfolk keytar. 90''s mumblecore readymade next level excepteur pinterest.\r\n\r\nHeirloom in lo-fi, in freegan edison bulb polaroid. Enim mollit ad veniam voluptate wolf. Semiotics master cleanse gochujang et sartorial small batch brooklyn post-ironic aute. Actually ad venmo, pariatur jean shorts leggings next level listicle aute direct trade copper mug tacos gastropub. Butcher raw denim chia tote bag, laborum freegan id adaptogen tilde keffiyeh single-origin coffee pour-over lomo meditation. Tote bag lorem knausgaard heirloom vexillologist, fingerstache viral subway tile ut.\r\n\r\nChia aliquip selvage sed velit selfies. Photo booth sint coloring book offal, enamel pin unicorn commodo consectetur elit live-edge schlitz pinterest exercitation. Kinfolk kombucha consequat woke sint meditation. Cred salvia tacos activated charcoal street art heirloom beard seitan brunch.\r\n\r\nSquid fam semiotics ennui, nisi ea synth man bun slow-carb proident tote bag etsy la croix. Lomo aesthetic VHS, id exercitation 8-bit try-hard aute ut you probably haven''t heard of them. Proident bushwick fanny pack, id hammock kale chips occupy lomo normcore velit fashion axe intelligentsia subway tile echo park. Everyday carry iPhone austin, adipisicing four loko edison bulb hoodie poutine flannel commodo non tumblr. Direct trade vaporware vexillologist blue bottle celiac.\r\n\r\nTempor slow-carb sriracha, fashion axe tumeric hexagon fanny pack hell of synth ad tbh ex. Vice est etsy in, coloring book jianbing freegan listicle copper mug next level. Godard reprehenderit glossier, nisi biodiesel artisan qui hashtag flexitarian. Est paleo chartreuse, shabby chic cray +1 af austin gluten-free four loko. Truffaut vegan pitchfork mumblecore synth, chambray everyday carry chartreuse kitsch dolor tumblr. Irure eu tacos art party, fanny pack kickstarter dolor +1 ut marfa freegan etsy trust fund sunt. Yuccie tempor microdosing VHS pickled aesthetic air plant, mlkshk man bun.', 4, '2018-11-12 20:35:54');

-- --------------------------------------------------------

--
-- Table structure for table `members`
--

CREATE TABLE IF NOT EXISTS `members` (
  `IDmbr` int(6) NOT NULL,
  `firstName` varchar(25) NOT NULL,
  `lastName` varchar(25) NOT NULL,
  `email` varchar(50) NOT NULL,
  `user` varchar(15) NOT NULL,
  `pswd` varchar(150) NOT NULL,
  `joinTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `members`
--

INSERT INTO `members` (`IDmbr`, `firstName`, `lastName`, `email`, `user`, `pswd`, `joinTime`) VALUES
(3, 'Titus', 'Peoples', 'tpeoples87@gmail.com', 'titus', '$2y$10$24CK2nu4RnpUGIcakKAvIOuEHkO2jUv/Nn7tK.QGe.ui/rJOY3Gou', '2018-12-04 20:03:18'),
(4, 'Ultimate', 'Entertainment', 'eye4star@yahoo.com', 'ulti', '$2y$10$UePLan6QpPHRWdBb82HwkeRSEfC.hJ9CMpQ6Gz4DbaUOjbsAvUDW6', '2018-12-04 20:30:50');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogs`
--
ALTER TABLE `blogs`
  ADD PRIMARY KEY (`IDblog`);

--
-- Indexes for table `members`
--
ALTER TABLE `members`
  ADD PRIMARY KEY (`IDmbr`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogs`
--
ALTER TABLE `blogs`
  MODIFY `IDblog` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=11;
--
-- AUTO_INCREMENT for table `members`
--
ALTER TABLE `members`
  MODIFY `IDmbr` int(6) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=13;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
